
name: Blogging Application Code Review, Build and Publish Job

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  codeql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: java

    - name: Run CodeQL analysis
      uses: github/codeql-action/analyze@v1

  
  build:

    runs-on: ubuntu-latest
    needs: codeql
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B -DskipTests=true package --file pom.xml

  publish-job:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn --batch-mode --update-snapshots verify -DskipTests=true
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging

    - name: Deploy Java Application
      run: |
        # Placeholder example: Deploying to GitHub Releases
        # Create a release
        gh release create v1.0.0 target/*.jar -n "Release v1.0.0"

    - name: Upload CodeQL results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ./codeql-results/codeql.sarif

  
